### PR TITLE
Added dependencies to bower and componentjs defs.

### PR DESCRIPTION
**Pull request by IvanSanchez**

### CODE REVIEW

**Comment by tmcw** [comment]
Hm, I don't quite know how component/bower dependencies work... will this install leaflet alongside leaflet-pip? Error if it isn't installed? Fwiw, leaflet-pip is compatible with both mapbox.js and leaflet, and I doubt that either package manager would be able to grep the difference.

**Comment by IvanSanchez** [comment]
This pulls leaflet alongside leaflet-pip (as demonstrated by running `bower install https://github.com/IvanSanchez/leaflet-pip.git#f9ce743e` in an empty dir). This also tells build systems to minify leaflet before leaflet-pip.

And now that I look into it: yes, both package managers are quite naïve, and don't seem to handle alternative dependencies :-(

**Comment by IvanSanchez** [comment]
Apparently the issue of alternative dependencies was discussed in bower over two years ago: https://github.com/bower/bower/issues/173

**Comment by tmcw** [comment]
I'd kind of prefer to keep the bower/component packages very slim, and not expect them to be mature about dependencies: use npm+browserify, or use downloads.

**Pull request closed without merging**
